"""Add status and analysis_type columns

Revision ID: 317d5f6ddfb6
Revises: 757d9eed2924
Create Date: 2025-12-08 04:43:02.498911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317d5f6ddfb6'
down_revision: Union[str, Sequence[str], None] = '757d9eed2924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('status', sa.String(length=20),server_default="in_progress", nullable=False))
    op.add_column('analysis_results', sa.Column('analysis_type', sa.String(length=20), server_default="general", nullable=False))
    op.create_unique_constraint(None, 'analysis_results', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis_results', type_='unique')
    op.drop_column('analysis_results', 'analysis_type')
    op.drop_column('analysis_results', 'status')
    # ### end Alembic commands ###
